MISSING_RATE_THRESHOLD_RED = 80
MISSING_RATE_THRESHOLD_YELLOW = 95

PRIMARY_KEY = ["SK_ID_PREV", "SK_ID_CURR", "MONTHS_BALANCE"]

NUMERICAL_DISCRETE_VARS = [
    "SK_ID_PREV",
    "SK_ID_CURR",
    "MONTHS_BALANCE",
    "CNT_DRAWINGS_ATM_CURRENT",
    "CNT_DRAWINGS_CURRENT",
    "CNT_DRAWINGS_OTHER_CURRENT",
    "CNT_DRAWINGS_POS_CURRENT",
    "CNT_INSTALMENT_MATURE_CUM",
    "SK_DPD",
    "SK_DPD_DEF",
]
NUMERICAL_CONTINUOUS_VARS = [
    "AMT_BALANCE",
    "AMT_CREDIT_LIMIT_ACTUAL",
    "AMT_DRAWINGS_ATM_CURRENT",
    "AMT_DRAWINGS_CURRENT",
    "AMT_DRAWINGS_OTHER_CURRENT",
    "AMT_DRAWINGS_POS_CURRENT",
    "AMT_INST_MIN_REGULARITY",
    "AMT_PAYMENT_CURRENT",
    "AMT_PAYMENT_TOTAL_CURRENT",
    "AMT_RECEIVABLE_PRINCIPAL",
    "AMT_RECIVABLE",
    "AMT_TOTAL_RECEIVABLE",
]
CATEGORICAL_NOMINAL_VARS = [
    "NAME_CONTRACT_STATUS",
]
CATEGORICAL_ORDINAL_VARS = []
TIME_VARS = []

APPLICATION_DATE = "2013-01-01"
DEFAULT_THRESHOLD = 3  # months
WRITE_OFF_THRESHOLD = 6  # months
DELINQUENCY_THRESHOLD = 2  # months
STICKINESS_PERIOD = 1  # months
PROBATION_PERIOD = 12  # months
INACTIVITY_PERIOD = 4  # months
TRANSACTOR_PERIOD = 2  # months
