APPLICATION_DATE = "2013-01-01"
DEFAULT_THRESHOLD = 3  # months
WRITE_OFF_THRESHOLD = 6  # months
DELINQUENCY_THRESHOLD = 2  # months
STICKINESS_PERIOD = 1  # months
PROBATION_PERIOD = 12  # months
INACTIVITY_PERIOD = 3  # months
TRANSACTOR_PERIOD = 4  # months
